from generic_getter import getter
files = [
"Abaecin.fasta",
"AlphaDefensin.fasta",
"Ascaphin.fasta",
"Aurein.fasta",
"Bacteriocin.fasta",
"BetaDefensin.fasta",
"Bombinin.fasta",
"Brevinin.fasta",
"Caerin.fasta",
"Cathelicidin.fasta",
"Cecropin.fasta",
"Clavanin.fasta",
"Coleoptericin.fasta",
"Cupiennin.fasta",
"Cyclotide.fasta",
"Cystatin.fasta",
"Dermaseptin.fasta",
"Esculentin.fasta",
"Formaecin.fasta",
"Hevein.fasta",
"Histone.fasta",
"Lectin.fasta",
"Magainin.fasta",
"Mastoparan.fasta",
"Ocellatin.fasta",
"Palustrin.fasta",
"Phylloseptin.fasta",
"Pseudin.fasta",
"Ribosome.fasta",
"Rugosin.fasta",
"Snakin.fasta",
"Temporin.fasta",
"Thionin.fasta"]
urls = [f"https://raw.githubusercontent.com/gmit-amp-res/amp/main/data/{file}" for file in files]
getter(urls, raw_folder = "../../raw_data/amp/")